-- 코드를 작성해주세요
SELECT ID, (CASE 
             WHEN (RK / (SELECT COUNT(*) FROM ECOLI_DATA) > 0.75) THEN 'LOW'
             WHEN (RK / (SELECT COUNT(*) FROM ECOLI_DATA) > 0.5) THEN 'MEDIUM'
             WHEN (RK / (SELECT COUNT(*) FROM ECOLI_DATA) >= 0.25) THEN 'HIGH'
            ELSE 'CRITICAL'
            END) AS COLONY_NAME
FROM (SELECT ID, RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS RK
    FROM ECOLI_DATA) ED
ORDER BY ID

