-- 코드를 입력하세요
SELECT DISTINCT HISTORY_ID,ROUND((DAY*(100-(CASE WHEN DAY >= 90 THEN (SELECT DISCOUNT_RATE
                                        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                                        WHERE DURATION_TYPE = '90일 이상' AND CAR_TYPE = '트럭')
                         WHEN DAY >= 30 THEN (SELECT DISCOUNT_RATE
                                        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                                        WHERE DURATION_TYPE = '30일 이상' AND CAR_TYPE = '트럭')
                         WHEN DAY >= 7 THEN (SELECT DISCOUNT_RATE
                                        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                                        WHERE DURATION_TYPE = '7일 이상' AND CAR_TYPE = '트럭')
                         ELSE 0 END)) / 100 * TRUCK.DAILY_FEE),0) AS FEE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCDP JOIN 
    (SELECT HISTORY_ID, CAR_TYPE, DATEDIFF(END_DATE,START_DATE)+1 AS DAY, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR CRCC JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH ON CRCC.CAR_ID = CRCRH.CAR_ID 
    WHERE CRCC.CAR_TYPE = '트럭') TRUCK ON CRCDP.CAR_TYPE = TRUCK.CAR_TYPE
WHERE DAY != 0
ORDER BY FEE DESC, HISTORY_ID DESC

