-- 코드를 작성해주세요
SELECT YEAR, (A.B - E.SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM ECOLI_DATA E JOIN (
    SELECT MAX(SIZE_OF_COLONY) AS B, YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)) A ON YEAR(E.DIFFERENTIATION_DATE) = A.YEAR
ORDER BY YEAR, YEAR_DEV 
      