-- 코드를 작성해주세요
SELECT SUM(SCORE) AS SCORE, HE.EMP_NO, HE.EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES HE JOIN HR_DEPARTMENT HD ON HE.DEPT_ID = HD.DEPT_ID
                     JOIN HR_GRADE HG ON HE.EMP_NO = HG.EMP_NO
WHERE HG.YEAR = '2022'
GROUP BY HG.EMP_NO
ORDER BY SCORE DESC
LIMIT 1